openapi: 3.0.0

info:
  version: 1.0.0
  title: Simple Rest API

tags:
  - name: SimpleRest
    description: Simple rest CRUD API

paths:
  #/add:
  #  post:
  #/getAll:


  /get/{id}:
    get:
      tags:
        - SimpleRest
      summary: Get one record by id
      description: Get one record by id
      operationId: get
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: Person
        '404':
          description: Request failed - No items

  #/update/{id}:
  #  put:
  #/delete/{id}:
  #  delete:

components:
  parameters:
    id:
      in: path
      name: id
      required: true
      description: record id
      schema:
        type: integer
